kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: metrics-server-practice
nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        v: "4"
- role: worker
  image: kindest/node:v1.28.0
